### ISSUE TITLE
Payment method token is not saved, customer's default payment method is charged

### ISSUE THREAD

**Issue by theunraveler** [killbill/killbill-braintree-blue-plugin#3]
It seems that this plugin does not actually store the actual payment method token for each payment method, but rather just the Braintree customer ID.

For example, I have 2 different accounts in KillBill that each have different payment methods associated with them:
![pm1](https://cloud.githubusercontent.com/assets/145273/9310703/0a73c37a-44d7-11e5-948c-90e1f53677f2.png)
![pm2](https://cloud.githubusercontent.com/assets/145273/9310707/0ee72b7c-44d7-11e5-80a7-19ebe40e3da2.png)
The payment methods belong to the same customer in Braintree. It seems to me that this plugin in interacting with the Braintree API with the customer ID instead of the payment method token, so instead of charging the correct card, whichever payment method is set as the customer's default in Braintree is charged. So in the above case, the Visa ending in 5027 was charged for both accounts since it is that customer's default payment method in Braintree.

Please let me know if you need more information. Thanks!

**Comment by pierre** [comment]
Looking at your screenshot, it looks like both payment methods have the same token. Can you share your `add_payment_method` call, the plugin tables content and the gateway logs (scrubbed)?

That being said, it looks like the `customer_id` is used by [default](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/braintree_blue.rb#L540) indeed unless `payment_method_token` is set. Could you try an auth call by passing the plugin property `payment_method_token=true` (if that works, we should probably make it default in the plugin)?

**Comment by theunraveler** [comment]
Hey Pierre,

Thanks for having a look. Here's the info you requested:
- `add_payment_method` call: https://gist.github.com/theunraveler/bfc7b9aae25e59b40768
- plugin table content: https://gist.github.com/theunraveler/a25f901cee4508dc372a
- I'm not sure where to find the gateway logs.

Also, I'm not sure what you mean by "try an auth call by passing the plugin property `payment_method_token=true`".

So yeah, it looks to me like the customer ID is being saved as both the `braintree_customer_id` and the `token` in the database. So perhaps it's a matter both of the plugin not saving the right thing to the database, then also not using the proper field for authorizing with Braintree?

**Comment by pierre** [comment]
> I'm not sure where to find the gateway logs

They should show up automatically with the main Kill Bill logs, provided you install the [default plugins](http://search.maven.org/remotecontent?filepath=org/kill-bill/billing/killbill-platform-osgi-bundles-defaultbundles/0.2/killbill-platform-osgi-bundles-defaultbundles-0.2.tar.gz). You can also increase the verbosity by setting:

```
:logger:
  :debug: true
```

in your yml configuration.

> Also, I'm not sure what you mean by "try an auth call by passing the plugin property payment_method_token=true".

In any payment API, you can pass special properties in the query parameters (e.g. `?pluginProperty=payment_method_token=true`) which will be passed through to the plugin (and ActiveMerchant). See our [payment docs](http://docs.killbill.io/0.14/userguide_payment.html#_plugin_properties).

> So perhaps it's a matter both of the plugin not saving the right thing to the database, then also not using the proper field for authorizing with Braintree?

It looks like a combination of things is happening:
- the token wasn't saved properly
- the default ActiveMerchant implementation relies on customer ids, not tokens. Setting `payment_method_token=true` seems to do the trick

Could you give https://github.com/killbill/killbill-braintree-blue-plugin/commit/9061792036ee8645ff40d25d79eb8984361b5a11 a try? Also, let me know if your import scripts are still working regarding importing the expiration date (when setting `skip_gw=true`).

**Comment by theunraveler** [comment]
Hey Pierre,

Thanks so much for looking at this! I think the logic for charging payment methods is correct--I've tested it in our lab and it seems to work fine. However, this does not allow for the token to be specified when creating the payment method with the `skip_gw` plugin property, so I made another pull request for that: https://github.com/killbill/killbill-braintree-blue-plugin/pull/4.

**Comment by pierre** [comment]
> I think the logic for charging payment methods is correct--I've tested it in our lab and it seems to work fine. 

Great! Thanks for double checking.

> However, this does not allow for the token to be specified when creating the payment method with the `skip_gw` plugin property, so I made another pull request for that: https://github.com/killbill/killbill-braintree-blue-plugin/pull/4.

Just merged it.
